daemon off;
worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;

    server {
        listen PORTAL_PORT;
        root DATA_DIR;
        index index.html;

        location /pdfs/ {
            alias DATA_DIR/pdfs/;
            autoindex on;
        }

        location /other/ {
            alias DATA_DIR/other/;
            autoindex on;
        }
    }
}
